mParticle/mparticle-apple-sdk

mParticle-Apple-SDK/Kits/MPKitProtocol.h
mParticle-Apple-SDK/mParticle.h
mParticle-Apple-SDK/mParticle.m

(See http://useyourloaf.com/blog/using-objective-c-lightweight-generics/ on Objective-C generics)
Because the callback for `checkForDeferredDeepLinkWithCompletionHandler` traces its NSDictionary all the way back to `[Branch getLatestReferringParams]`, which doesn’t specify generics for NSDictionary, there is no guarantee that the keys and values will be of type `<NSString *, NSString *>`. This proves to be an issue when bridging to Swift, as there are times when `[Branch getLatestreferringParams]` _can_ return a dictionary of type `[NSObject : AnyObject]`, which causes a crash at runtime because Swift is expecting `[String : String]`, but is getting `[String : NSNumber]`.
Therefore, the callback can only be as specific as its upstream dependencies, which is to say, not at all. Thus, …

Remove NSDictionary generic specifications for checkForDeferredDeepLinkWithCompletionHandler callback

---

mParticle-Apple-SDK/Ecommerce/MPCommerceEvent.mm

Please, find more details in the issue.
https://github.com/mParticle/mparticle-apple-sdk/issues/56
MPCommerce event losing a currency property after being copied.

copy currency property in MPCommerceEvent

---

mParticle-Apple-SDK/Ecommerce/MPCommerceEvent+Dictionary.h
mParticle-Apple-SDK/Ecommerce/MPTransactionAttributes+Dictionary.h

There are two files that are missing the direct import for the category definitions that they create. This allows those files to be built if the top-level header is not directly added.
Built into the Airbnb Alpha app.
No formal issue created. Discussion on mParticle Slack channel only.

Add imports for category definitions

---

UnitTests/MPPersistenceControllerTests.mm
mParticle-Apple-SDK/Persistence/MPDatabaseMigrationController.m
mParticle-Apple-SDK/Persistence/MPPersistenceController.mm

Using the the quotations for imports conflicts with other sqlite pods that may be included from other dependencies causing a 
sqlite.h file not found
Build and run and observe a successful build result

Change imports to modular

---

mParticle-Apple-SDK.podspec

For this SDK to be specified as a dependency in another podspec, `s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }` must be added the podspec so integrating applications do not have to respecify the dependency using `modular_header`
Tested using a private podspec in our internal setup

Add missing DEFINE_MODULE

---

README.md

Markdown table format is now OK
The table was broken, because it has some markdown mistakes.

Update Markdown Table

---

mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/mParticle.m

On mParticle's Web and Android SDK's it's possible to retrieve the current sessions start time:
MParticle.getInstance()?.currentSession?.sessionStartTime
Web - mParticle.Store.sessionStartDate.getTime()
Currently on the iOS SDK MPSession is internal only while MParticleSession is what is provided to users (which doesn't expose the session start time property).

fix: Expose Session Start Time

---

UnitTests/MPUploadBuilderTests.m
mParticle-Apple-SDK/Utils/MPUploadBuilder.mm

Basically the device Info that's used for the event batch comes from the MPSession saved to the local database. So that saved version of the deviceInfo wasn't getting updated until a new session is created (restart). ATT and IDFA were implemented before we began [caching app and device info](https://github.com/mParticle/mparticle-apple-sdk-internal/pull/17/files#diff-4166039127eb7c02c467286fe092e331049fc718b8770abc7ffcf78fe061b8d5R159) so it been broken in this way since that change.
Tested using sample App
Closes https://go.mparticle.com/work/76333

Fix: Correct IDFA Enrichment when Changed during Session

---

Scripts/carthage.sh

Since the Github runners switched to defaulting to Xcode 13, the *.framework builds for iOS stopped working (*.xcframework builds still worked).
Turns out it was a pretty simple change to our build script to work for Xcode 13 (previously was Xcode 12 only).
Merging this directly to main since it's CI that needs to run on next release.
Tested the build locally on my machine and it works correctly (also updated the latest release to include the iOS framework artifacts)
Closes https://go.mparticle.com/work/SQDSDKS-3550

ci: fix building of *.framework artifacts for iOS

---

mParticle-Apple-SDK/AppNotifications/MPAppDelegateProxy.m

Adds an implementation of `conformsToProtocol:` to `MPAppDelegateProxy` that bubbles up protocol implementations from the base AppDelegate. Issue is described in #143.
Had to add an extra singleton in order to get the original app delegate types. If anyone can think of a better way, input is extremely welcome. 
Manually smoke tested in our setup, and unit tested. Should be low-to-no impact for other integrations, but unknown.
Implementation as described in [#143](https://github.com/mParticle/mparticle-apple-sdk/issues/143)

Adds conformsToProtocol forwarding to MPAppDelegateProxy

---

UnitTests/MPUploadBuilderTests.m
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/Utils/MPUploadBuilder.mm

This PR implements support for allowing SDK batches of data to be passed through a customer callback where they can be modified or dropped.
- Unit testing
- Manual testing
Closes https://go.mparticle.com/work/3733

feat: add support for client side rules

---

UnitTests/MPKitContainerTests.m
UnitTests/MPURLRequestBuilderTests.m
mParticle-Apple-SDK/Kits/MPKitContainer.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Network/MPURLRequestBuilder.m

The "x-mp-kits" header field was previously sending a list of kits that were actively receiving events. Now it will send a list of kits that have been configured, even if they are not actively receiving events due to the SDK state. For Example, a kit that was shut down due to the current user's logged-in status not matching its configurations directive previous would not have been included in this list but now will be included
Modified a few existing tests to include checks for the new `[kjitContainer configuredKits]` method where the results would differ from `[kitContainer activeKits]`. Also included a new unit test with a more focused scenario. Updated a networking tests to make sure the `configuredKits` method was properly being applied to `x-mp-kits`
Closes …

fix: update active kits header

---

Example/mParticleExample/ViewController.m
UnitTests/MPEventTests.mm
mParticle-Apple-SDK/Utils/NSDictionary+MPCaseInsensitive.m

We discussed this in stand up and determined it makes sense to have iOS match Android behavior in terms of serializing dictionaries when sending to the server but leave the objects as-is when passing to kits. 
Updated unit test to include cases with dictionaries
Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4087

feat: match android type support for custom attributes

---

.github/workflows/cross-platform-tests.yml
.github/workflows/native-tests.yml
UnitTests/MPEventTests.mm
UnitTests/MPPersistenceControllerTests.mm
mParticle-Apple-SDK/Include/NSDictionary+MPCaseInsensitive.h
mParticle-Apple-SDK/Utils/NSDictionary+MPCaseInsensitive.m

This is an inconsistency between data planning and iOS. Android support this without issue. Based on those two inconsistencies, I’m rationalizing this as a bug.
Context: In JSON schema, there is a difference between null and missing, and therefore in our data planning feature, we allow you to specific that event attributes can be null. Steps to repro:
Create a data plan that with an event containing an event attribute value that is both both required and to allowed to be null (note, this is different than optional/not-required, you need to literally specify that the value is allowed to be nullable)
With the Apple SDK, create an event with nsnull as an event attribute value
when the SDK uploads, in live stream and in the data planning violation report, it’ll say that a required attribute …

fix: Allow null event attributes

---

mParticle-Apple-SDK/Data Model/MPSegment.m
mParticle-Apple-SDK/Kits/MPKitActivity.m
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/Utils/MPStateMachine.mm
mParticle-Apple-SDK/mParticle.m

Remove calls to removeObserver no longer necessary now that we no longer support iOS 8
Validated per Apple [docs](https://developer.apple.com/documentation/foundation/nsnotificationcenter/1413994-removeobserver) that this is no longer necessary since observer will be removed automatically.
Closes https://go.mparticle.com/work/SQDSDKS-4830

fix: remove unnecessary calls to remove observer

---

mParticle-Apple-SDK/Custom Modules/MPCustomModule.m
mParticle-Apple-SDK/Data Model/MPBreadcrumb.m
mParticle-Apple-SDK/Data Model/MPConsumerInfo.mm
mParticle-Apple-SDK/Data Model/MPForwardRecord.mm
mParticle-Apple-SDK/Data Model/MPMessage.m
mParticle-Apple-SDK/Data Model/MPSegment.m
mParticle-Apple-SDK/Data Model/MPSegmentMembership.m
mParticle-Apple-SDK/Data Model/MPSession.m
mParticle-Apple-SDK/Data Model/MPUpload.m
mParticle-Apple-SDK/Data Model/MParticleUserNotification.m
mParticle-Apple-SDK/Ecommerce/MPCommerceEvent.mm
mParticle-Apple-SDK/Ecommerce/MPProduct.mm
mParticle-Apple-SDK/Ecommerce/MPPromotion.mm
mParticle-Apple-SDK/Ecommerce/MPTransactionAttributes.m
mParticle-Apple-SDK/Event/MPBaseEvent.m
mParticle-Apple-SDK/Event/MPEvent.m
mParticle-Apple-SDK/Kits/MPAttributeProjection.m
mParticle-Apple-SDK/Kits/MPBaseProjection.m
mParticle-Apple-SDK/Kits/MPEventProjection.mm
mParticle-Apple-SDK/Kits/MPKitConfiguration.mm

All instances where `isEqual:` implemented should also implement `hash`
Ran sample app and unit tests
Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4834

fix: Add Hash Methods where isEqual called

---

mParticle-Apple-SDK/Utils/MPApplication.m

Inspected all uses of dealloc method
MPApplication
Removed as synchronize has been unneeded since iOS 7
MPBackendController
 Our in-app documentation provides full reasoning for this code as it supports our proxying of the app delegate.
MPSegment
[Apple Docs](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/Articles/KVOBasics.html) (_"A typical pattern is to register as an observer during the observer’s initialization (for example in init or viewDidLoad) and unregister during deallocation (usually in dealloc)"_) actually suggest including your removeObserver code in the dealloc: method. Adding the observer doesn’t cause a retain on the class object and using instruments I wasn’t able to find any leaks. If you have a .trace recorded from …

fix: Remove Unnecessary Synchronize in Dealloc

---

mParticle-Apple-SDK/Utils/MPApplication.m

We use `_dyld_register_func_for_add_image` to register a callback function to receive a list of all loaded dynamic libraries. We are using this to include that information with error and exception reports from customers when they call the -[MParticle logError] or -[MParticle logException] methods.
Previously we registered this callback in the `init` method of `MPApplication`, however that object may be initialized many times during the course of an app session. This can cause a high number of unnecessary function pointer allocations to the callback function.
I've moved this to the `initialize` method so that it will only be called once per app session, which is all we need. This will resolve the allocations issue as it will now only allocate a single pointer.
Tested in a sample app to …

fix: Move _dyld_register_func_for_add_image call to initialize

---

Example/mParticleExample/ViewController.m
UnitTests/MParticleTests.m
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/mParticle.m

Implement a method to allow upload interval to be changed after SDK initialization.
Added Unit tests and updated example app
Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4948

feat: Allow uploadInterval to be set manually

---

mParticle-Apple-SDK/Include/MPEnums.h
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/mParticle.m

Add ability for wrapper SDKs to set their name and version on the core SDK.
Tested locally.
Closes https://go.mparticle.com/work/SQDSDKS-4756

feat: Add wrapper sdk info setter

---

mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Persistence/MPPersistenceController.mm
mParticle-Apple-SDK/Utils/MPStateMachine.h
mParticle-Apple-SDK/Utils/MPStateMachine.mm

Prevent storage of the SDK from growing indefinitely if we don't have a valid key and thus can't upload
Tested using an iOS sample app with an invalid key and secret
Closes https://go.mparticle.com/work/SQDSDKS-4796

feat: Block writes on invalid API key based on Identity/Config responses

---

mParticle-Apple-SDK/Network/MPNetworkCommunication.m

- Fix identify API call using CNAME domain
- Tested locally using a test app with custom CNAME domains that previously didn't work
- Closes https://go.mparticle.com/work/SQDSDKS-5025

fix: Identify API call using CNAME domain

---

README.md
mParticle-Apple-SDK.podspec
mParticle-Apple-SDK/Include/MPKitProtocol.h
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Location/MPLocationManager.h
mParticle-Apple-SDK/Location/MPLocationManager.m
mParticle-Apple-SDK/MPBackendController.h
mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/Utils/MPCurrentState.m
mParticle-Apple-SDK/Utils/MPMessageBuilder.h
mParticle-Apple-SDK/Utils/MPMessageBuilder.mm
mParticle-Apple-SDK/Utils/MPResponseConfig.m
mParticle-Apple-SDK/Utils/MPStateMachine.h
mParticle-Apple-SDK/Utils/MPStateMachine.mm
mParticle-Apple-SDK/mParticle.m

- These commits give two options for the issue where clients attempts at publishing are triggering the NSLocationAlwaysAndWhenInUsageDescription flag from Apple. The first commit expands the pre processor flag to a CLLocation call that was not included before. The second commit removes all uses of CLLocation. When reviewing please give your opinion on which is the preferred solution.
- Both commits tested on simulator to confirm no crash or issue in that respect
- Closes https://go.mparticle.com/work/SQDSDKS-4997

fix: Correct location flag issue when publishing

---

UnitTests/MPSwiftTests.swift
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Include/MPEnums.h

- Add missing MPIdentityErrorResponseCode values
resolves https://github.com/mParticle/mparticle-apple-sdk/issues/178
- Added unit test in Swift to ensure the new values are available as the original bug was due to Swift bridging.
- Closes https://go.mparticle.com/work/SQDSDKS-5024

fix: Add missing MPIdentityErrorResponseCode values

---

Package.swift
README.md
SPM/mParticle-Apple-SDK-NoLocation
mParticle-Apple-SDK.podspec

- fix: Add missing no location target for SPM
- Tested locally using an SPM test project, confirmed both targets work correctly using `strings` command
- Closes https://go.mparticle.com/work/SQDSDKS-5079

fix: Add missing no location target for SPM

---

UnitTests/MPCommerceEventTests.m
mParticle-Apple-SDK/Utils/NSNumber+MPFormatter.m

- Change number formatter to 2 decimals
- Tested locally and updated unit test to check
- Closes https://go.mparticle.com/work/SQDSDKS-4795

fix: Limit Currency Values to 2 Decimal Points

---

UnitTests/MPKitContainerTests.m
UnitTests/MPKitTestClassSideloaded.h
UnitTests/MPKitTestClassSideloaded.m
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Include/MPKitProtocol.h
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Kits/MPKitContainer.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Kits/MPKitRegister.mm
mParticle-Apple-SDK/mParticle.m

This adds the ability to "sideload" local custom kits.
The difference between these kits and normal kits is that they do not receive a server side configuration and are always activated. Registration is done locally, and these kits will receive all of the usual MPKitProtocol callback method calls. Some use cases include debugging (logging all MPKitProtocol callbacks) and creating custom integrations that are not yet officially supported.
At the moment, all events are forwarded as event filtering is not yet supported. This will come in a future release.
- Added unit tests
- Tested functionality in a local test app
- Closes https://go.mparticle.com/work/SQDSDKS-5111

feat: Custom local kit loading aka kit sideloading

---

UnitTests/MParticleOptionsTests.m
mParticle-Apple-SDK/Utils/MPSearchAdsAttribution.m
mParticle-Apple-SDK/mParticle.m

- Implement Apple Search Ads for Attribution in way similar to our existing attribution support for ADClient
- Tested locally on simulator
- Closes https://go.mparticle.com/work/SQDSDKS-5122

feat: Use Apple Search Ads for Attribution

---

UnitTests/MPUploadBuilderTests.m
mParticle-Apple-SDK/MPBackendController.mm
mParticle-Apple-SDK/Utils/MPUploadBuilder.mm

- ensured only userIdentities and not all identities are being included in the userIdentities section of the upload
- Tested locally using attached data plan and my workspace livestream
- Closes https://go.mparticle.com/work/SQDSDKS-5233

fix: Prevent Unplanned User Identities

---

.github/workflows/sdk-release.yml
Scripts/release.sh

- Upload build artifacts used by SPM to an S3 bucket to work around an Xcode bug that unnecessarily requires credentials to download artifacts from the Github release which breaks CI for some users.
- Tested each piece independently (tested uploading to this S3 bucket using these credentials, tested running the release script but uploading to a test bucket on a fork to show that the env variables would work inside the release script)
- Can't do a full end to end test until our next release of the SDK, but everything should work, and if we run into issues, changes should be minimal as all pieces have been validated. 
- Closes https://go.mparticle.com/work/SQDSDKS-5416

feat: Upload build artifacts to S3 for SPM

---

UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Kits/MPKitContainer.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Kits/MPSideloadedKit.swift

- Update public API to use MPSideloadedKit object in preparation for filtering support.
- Unit tests updated and ran locally (also run in CI).
- Closes https://go.mparticle.com/work/SQDSDKS-5483

feat: Add Sideloaded Kit Filtering Support to API

---

README.md
mParticle-Apple-SDK/Swift.h

- React Native was having trouble with the imports and in the process of correcting the imports for that we realized 'use_frameworks!' was no longer required for initializing with cocaopods.
- Tested for React Native, Cocaopods, and SPM for Location and No-Location builds
- Closes https://go.mparticle.com/work/SQDSDKS-5564

fix: Update imports for react native compatibility

---

README.md

- `use_frameworks!` for a period of time was required to solve several issues when importing 3rd party libraries including this sdk. Recently with Swift static framework support it no longer became required for our SDK
- Tested across all forms of SDK integration
- Closes https://go.mparticle.com/work/SQDSDKS-5564

docs: Update Readme for use_frameworks! updates

---

UnitTests/MParticleTests.m

We were previously directly checking the internal obj-c string class name in 2 unit tests. This has changed to the internal swift class name in iOS 17/Xcode 15. I modified the checks to use the more generic `isKindOfClass:` and now they work on both iOS 17 and earlier versions.
- Tests confirmed using both Xcode 14 and 15
- Closes https://go.mparticle.com/work/SQDSDKS-5711

test: Update string check for Xcode 15 compat

---

mParticle-Apple-SDK/Utils/MPDevice.m

We have a failing unit test on Xcode 15/iOS 17 due to a change in the way the locale/language string is generated in MPDevice.
`/Users/dev/mparticle-apple-sdk/UnitTests/MPDeviceTests.m:40 testDictionaryDescription: ((testDictionary[@"dll"]) equal to (@"en")) failed: ("en-US") is not equal to ("en")`
It looks like iOS 17 now uses the full ISO language + location string (`en-US`) in `[NSLocale preferredLanguages]` instead of just `en`.
Interestingly, according to Apple (and various SO question and blogs), they supposedly changed this format from “en” to “en-US” back in iOS 9…but I can confirm that in a test app if I run it on iOS 16, I get “en” and with no code changes, on iOS 17 I get “en-US”…
See this technical note here: [Technical Note TN2418: Language Identifiers in iOS, macOS, …

test: Ensure language code consistency on iOS 17

---

UnitTests/MPURLRequestBuilderTests.m

This test just confirms that if a customer sets their custom hosts incorrectly by prepending `https://`, the URL will be incorrect. In iOS 17 it's still incorrect, just in a slightly different way. This won't affect customers with currently correct configurations, so I've just adjusted the test to handle both formats.
- Confirmed it works on both iOS 16 and 17
- Closes https://go.mparticle.com/work/SQDSDKS-5712

test: Handle different URL formatting in iOS 17

---

.github/workflows/native-tests.yml

- Updates the CI to run tests using matrices of different Xcode and OS versions.
- Simplified yaml by using the matrix functionality for build scheme as well
This supersedes the previous PR here: https://github.com/mParticle/mparticle-apple-sdk/pull/214
- Tested in github actions on a test branch, all tests passed on both Xcode 14 and Xcode 15 beta
- Closes https://go.mparticle.com/work/SQDSDKS-5587

ci: GitHub Actions Xcode version test matrix

---

.github/workflows/sdk-release.yml
Scripts/make_artifacts.sh

- Update semantic release action to sign xcframeworks
- Signs using our distribution certificate that is in GitHub secrets
- E2E tested using a fork, signing worked perfectly, downloaded the build artifacts and confirmed signatures with `codesign -dvv mParticle_Apple_SDK.xcframework`
- Confirmed signing is detected properly in Xcode 15 UI and properly warns if signature changes
- Closes https://go.mparticle.com/work/SQDSDKS-5656

ci: Update semantic release action to sign xcframeworks

---

mParticle-Apple-SDK/AppNotifications/MPAppNotificationHandler.mm

- It was reported by one of our clients that push registration events were showing as 0 for Braze even though it was incrementing for the inbound count in the event forwarding view even though it was working as expected. After further investigation, I've noticed in our code that when we forward the call to the kits, its being passed as MPMessageTypeUnknown in stead of MPMessageTypePushRegistration which then is dropped since the if statement in kitContainer at line 2341 drops any event with MPMessageTypeUnknown
- [Y] Was this tested locally? If not, explain why.
- E2E testing
- Closes https://mparticle-eng.atlassian.net/browse/PRODRDMP-5650

fix:Push Registration events to show forwarded for kits

---

UnitTests/MPNetworkCommunication+Tests.h
UnitTests/MPNetworkCommunicationTests.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Utils/MPStateMachine.h

- Directly route to the correct pod using the api key prefix when feature flag is enabled
- Added unit tests
- E2E tested against all pods
- Closes https://go.mparticle.com/work/SQDSDKS-5771

feat: Direct routing to correct pod

---

UnitTests/MPNetworkCommunication+Tests.h
UnitTests/MPNetworkCommunicationTests.m
mParticle-Apple-SDK/MPIConstants.h
mParticle-Apple-SDK/MPIConstants.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Utils/MPResponseConfig.m
mParticle-Apple-SDK/Utils/MPStateMachine.h

- Directly route to the correct pod using the api key prefix when feature flag is enabled
- Fully tested using both production for routing logic and config parsing and QA for config parsing
- Closes https://go.mparticle.com/work/SQDSDKS-5862

feat: Direct routing to correct pod (#223) (#229)

---

UnitTests/HasherTests.mm
UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK/Include/MPIHasher.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Utils/MPIHasher.mm

- Currently the code that hashes each value and compares those hashes to the ones from the kit config is scattered all over the codebase. Since we’ll need to reuse that code in the MPSideloadedKit class to implement the “add filter” methods, we should first refactor it into a static utility class.
- Tested locally and with new unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-5343

feat: 5343 Refactor Kit Filter Hash Functions

---

.github/workflows/native-tests.yml

- Remove Xcode 14 from test matrix
- This is a CI only change, we'll confirm it when CI passes
- Closes https://go.mparticle.com/work/SQDSDKS-5907

ci: Remove Xcode 14 from test matrix

---

.github/workflows/native-tests.yml
mParticle-Apple-SDK/Network/MPConnector.m

- Starting with Xcode 15/iOS 17, there is a new warning in CFNetwork if you call `[NSURLSession uploadTaskWithRequest:fromData:]` if the request passed in already has its body set. In this case, we set the same data as the `HTTPBody` property of the request that we pass in to that method, so in the end the call worked fine, but now warns that we're setting it twice. Since we always set the post body on the request when we call `[MPURLRequestBuilder build]` on line 246, I've switched to using the more correct `[NSURLSession dataTaskWithRequest]` which just uses the HTTPBody from the request instead of the data we pass in. This works exactly the same, but fixes the warning.
- E2E tested using a test app
- Closes https://go.mparticle.com/work/SQDSDKS-5921

fix: CFNetwork upload warning setting body twice

---

UnitTests/MPIdentityApiRequestTests.m
UnitTests/MPIdentityCachingTests.m
UnitTests/MPIdentityTests.m
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Identity/MPIdentityApiManager.m
mParticle-Apple-SDK/Identity/MPIdentityApiRequest.m
mParticle-Apple-SDK/Identity/MPIdentityDTO.h
mParticle-Apple-SDK/Identity/MPIdentityDTO.m
mParticle-Apple-SDK/Identity/MParticleUser.m
mParticle-Apple-SDK/Include/MPIdentityApiRequest.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Persistence/MPIdentityCaching.h
mParticle-Apple-SDK/Persistence/MPIdentityCaching.m
mParticle-Apple-SDK/Utils/MPStateMachine.h

- Adds caching of identify and login calls
- Clears that cache on modify and logout calls
- Some minor code cleanup
This is all behind a feature flag that is currently disabled
- Unit tests were added
- Tested locally:
```
1. Disable feature flag
mParticle -> Identity response code: 200
mParticle -> Identity execution time: 437.32ms
mParticle -> Identity response:
{"context":null,"matched_identities":{"email":"bbaron+abc1@mparticle.com"},"is_ephemeral":false,"mpid":"6167123318226482339","is_logged_in":true}
2. Start app fresh (idenity should save to cache)
mParticle -> Identity Caching - max age header value (in seconds): 86400
mParticle -> Identity Caching - Cached response for endpoint 2, key: 2::8f9e2eefac54a94a33bcfa00512550bf4963e21ee01060a924fc181bd55981a0, expires: 2024-01-10 …
```

feat: Identity API response caching

---

UnitTests/MPNetworkCommunicationTests.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.m

- Add logic to route requests to the `tracking-` urls after a user accepts tracking (using ATT status), before accepting it should route to the current urls
- Tested normal function in sample app (using default URL) and updated unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6060

feat: Setup Logic for Tracking URL

---

.github/workflows/build-and-lint.yml
.github/workflows/cross-platform-tests.yml
.github/workflows/native-tests.yml
.github/workflows/sdk-release.yml

- Update all CI to use macOS-13 runners and Xcode 15.2
- Update all checkout actions to v4 as v3 uses a deprecated version of node
- The actions that run in this PR will test most of the changes, final test will happen when we cut the next release as it's not really possible to fully test the release action without running it, but my previous PR fixed building on Xcode 15, so it should work (release build scripts run locally to test Xcode 15.2 support)
- Closes https://go.mparticle.com/work/6171

ci: Use latest checkout action, macOS, and Xcode

---

mParticle-Apple-SDK.xcodeproj/project.pbxproj

- Add privacy manifest to build artifacts
- Tested release artifacts build script locally and confirmed that all frameworks and xcframeworks contain the privacy manifest
- Closes https://go.mparticle.com/work/SQDSDKS-6162

feat: Add privacy manifest to build artifacts

---

UnitTests/MPKitSecondTestClass.m
UnitTests/MPKitSecondTestClassNoStartImmediately.m
UnitTests/MPKitTestClass.m
UnitTests/MPKitTestClassNoStartImmediately.h
UnitTests/MPKitTestClassNoStartImmediately.m
UnitTests/MPKitTestClassSideloaded.m
UnitTests/MParticleTests.m
mParticle-Apple-SDK/Include/MPKitProtocol.h
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Kits/MPKitContainer.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Kits/MPKitRegister.m
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/mParticle.m

This new feature enables customers to switch to a new workspace while the app is running. It works by uploading any waiting events, completely resetting the internal data/state of the SDK, stopping/uninitializing any kits that support that (none do yet, but the logic is there to handle it), removing any kits that don't support reinitialization to prevent events forwarding to the wrong accounts, removing all sideloaded kits as new instances will be passed in again via the new MParticleOptions object, and then starts the SDK up fresh using the new API key.
NOTE: A change was made to MPKitProtocol to rename `deinit` to `stop` to prevent conflicts with Swift since it uses `deinit` rather than `dealloc` to deinitialize classes. No kits were using the `deinit` method in the protocol, so while …

feat: Switch workspaces without restarting app

---

UnitTests/MPPersistenceControllerTests.mm
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Identity/MPAudience.m
mParticle-Apple-SDK/Identity/MParticleUser.m
mParticle-Apple-SDK/Include/MPAudience.h
mParticle-Apple-SDK/Include/MParticleUser.h
mParticle-Apple-SDK/MPBackendController.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Persistence/MPPersistenceController.mm

- This reverts commit 1c04262a6144bd292d364873ca1701b0a3793136 and exposes a method to allow our users to request what audiences a user is part of.
- Tested using QA endpoints
- Closes https://go.mparticle.com/work/SQDSDKS-5993

feat: Add Audience Support Reverts(#171)"

---

UnitTests/MPBackendControllerTests.m
UnitTests/MPDataModelTests.m
UnitTests/MPMessageBuilderTests.m
UnitTests/MPPersistenceControllerTests.mm
UnitTests/MPUploadBuilderTests.m
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Utils/MPMessageBuilder.h
mParticle-Apple-SDK/Utils/MPMessageBuilder.m

closes https://github.com/mParticle/mparticle-apple-sdk/issues/256
After some investigation, it looks like the crash is happening due to memory corruption, specifically of the `messageDictionary` object in the `MPMessageBuilder` class, but only when the `withLocation:` method is called. It seems that the pointer referenced invalid memory... It's unclear whether the root cause it in the SDK code or external code clobbering that memory, but in an attempt to resolve the issue I've refactored the `MPMessageBuilder` class in the following ways:
- Make the `messageDictionary` object a (strong) property instead of an instance variable in case there's some kind of compiler issue preventing it from being properly strongly retained
- Simplify class by removing the `new` class methods and just using …

fix: Refactor MPUploadBuilder to attempt to eliminate rare crash in withLocation: method

---

mParticle-Apple-SDK/MPBackendController.m

- Fix occasion timing crash around log notification
1.  App goes to background for a long time (not killed)
2. User receives and taps notification
3. App opens and at the same, concurrently, time attempts to
a. on main queue, log user notification with _session property in https://github.com/mParticle/mparticle-apple-sdk/blob/d604e598b74503ff6f675c0989a014a0f266f21d/mParticle-Apple-SDK/MPBackendController.m#L1986 
b. on internal message queue, end old …

fix: Correct threading around user notification log

---

UnitTests/MPBackendControllerTests.m
UnitTests/MPBaseTestCase.h
UnitTests/MPForwardQueueItemTests.m
UnitTests/MPKitAPITests.m
UnitTests/MPKitActivityTests.m
UnitTests/MPKitContainerTests.m
UnitTests/MPNetworkCommunicationTests.m
UnitTests/MPPersistenceControllerTests.mm
UnitTests/MPResponseConfigTests.m
UnitTests/MPStateMachineTests.m
UnitTests/MPURLRequestBuilderTests.m
UnitTests/MPUploadBuilderTests.m
UnitTests/MParticleTests.m

After doing some digging it appears that the errors and other failed tests related to the kit registry were a red herring. What it appears was happening was that on a slow CI runner if one of the tests with chained calls to dispatch_after would time out, it would move on to the next tests but then a few seconds later it would finish which interfered with the data of other tests. The timing was set pretty tight, or rather plenty of time on a fast MacBook Pro, but tight on a slow CI runner. I've increased all timeouts to 15 seconds, which should be more than enough time for all runners to complete.
- Tests ran fine locally, but they always did... I'll be running them multiple times via this PR to confirm it succeeds every time.
- Closes https://go.mparticle.com/work/SQDSDKS-6230

ci: Increase timeout on unit test expectations

---

UnitTests/MPPersistenceControllerTests.mm
mParticle-Apple-SDK/Identity/MPAudience.m
mParticle-Apple-SDK/Identity/MParticleUser.m
mParticle-Apple-SDK/Include/MPAudience.h
mParticle-Apple-SDK/Include/MParticleUser.h
mParticle-Apple-SDK/MPBackendController.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.m

- Add methods to the public API to retrieve audience IDs associated with the current user
- Tested locally with hard coded data.
- Closes https://go.mparticle.com/work/SQDSDKS-6150

feat: Update Audience Logic

---

UnitTests/MPIdentityApiRequestTests.m
UnitTests/MPSwiftTests.swift
mParticle-Apple-SDK/Identity/FilteredMPIdentityApiRequest.m
mParticle-Apple-SDK/Identity/MPIdentityApiRequest.m
mParticle-Apple-SDK/Include/MPIdentityApiRequest.h

Fix crash when accessing the `-[MPIdentityApiRequest identity]` property from Swift due to incorrect type hinting
We had it hinted as `<NSNumber*, NSString*>` but then we also stored `NSNull` objects in some cases. That was fine with Objective-C since it ignores the type hints at runtime, but Swift doesn't and crashes if any NSNull objects are present when accessing the `identities` property.
Note this doesn't actually change the underlying behavior of this property in any way, it just now is correctly type hinted as `<NSNumber*, NSObject*>` to include the possibility of `NSNull`.
- First reproduced the crash, then confirmed that I can now access the property from Swift without crashing. Also added unit tests to confirm both the core behavior and the Swift interop, explicitly accessing …

fix: Type hinting MPIdentityApiRequest.identities

---

mParticle-Apple-SDK.podspec

- Update with suggestion from this [issue](https://github.com/mParticle/mparticle-apple-sdk/issues/269) to ensure that cocaopods users are correctly receiving the privacy manifest.
- unit tests ran and pod lib lint
- Closes https://github.com/mParticle/mparticle-apple-sdk/issues/269

Update mParticle-Apple-SDK.podspec for privacy manifest

---

UnitTests/MPBackendControllerTests.m
UnitTests/MPBaseTestCase.m
UnitTests/MPPersistenceControllerTests.mm
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Persistence/MPPersistenceController.mm
mParticle-Apple-SDK/Utils/MPStateMachine.h
mParticle-Apple-SDK/Utils/MPStateMachine.m
mParticle-Apple-SDK/mParticle.m

To prevent excessive database size for customers that do a lot of event logging, it's now possible to set a max persistence age for batches/sessions/uploads. This was already happening, but it defaulted to 90 days. Depending on the amount of events logged and whether a user blocks mParticle uploads or has poor internet connectivity, that could be way too long. Also, some customers may not be interested in events that happened so long ago.
With the new `persistenceMaxAgeSeconds` property in `MParticleOptions`, it's now possible to override that with any positive value.
Also, I reverted an older change that would attempt to detect when API keys were no longer valid to prevent excessive database growth because may cause false positives. For customers that are concerned about this, they can …

feat: Add max persistence age override option

---

mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/mParticle.m

- We already had an optional protocol method for this but weren't actually forwarding when set on mParticle object. This adds that forwarding as it's necessary for the latest Braze SDK update and iOS 17 app tracking stuff.
- E2E tested to see that the kit correctly received the status, tested with both an NSNumber and nil for the timestamp.
- Closes https://go.mparticle.com/work/SQDSDKS-6409

fix: Forwarding ATT status to kits

---

UnitTests/MPIdentityTests.m
mParticle-Apple-SDK/Identity/MPIdentityApi.m

- Changed functionality to handle situations when start and end time is nil more [like Android does](https://github.com/mParticle/mparticle-android-sdk/blob/2698bde6463d034258382b14e6fe5b824b56c9e4/android-core/src/main/java/com/mparticle/identity/AliasRequest.java#L159). Including using default start and end times if not set by the user.
- Tested manually on sample app and updated unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6324

fix: Allow Alias When Start and End Time Not Set

---

mParticle-Apple-SDK/Utils/MPApplication.h
mParticle-Apple-SDK/Utils/MPApplication.m
mParticle-Apple-SDK/Utils/MPStateMachine.m

We received a report of freezing causing due to retrieving the badge number count. While this appears to be an Apple bug, we not longer have any need for that information, so we've removed it entirely to prevent the potential freeze.
- Performed SDK smoke test using a test app
- Closes https://go.mparticle.com/work/SQDSDKS-6416

fix: Remove unnecessary badge number functionality

---

mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Utils/MPApplication.m
mParticle-Apple-SDK/Utils/MPSearchAdsAttribution.h
mParticle-Apple-SDK/Utils/MPSearchAdsAttribution.m
mParticle-Apple-SDK/Utils/MPStateMachine.h
mParticle-Apple-SDK/Utils/MPStateMachine.m

- Remove deprecated and no longer functional iAd framework code
- Replace unnecessary reflection with direct calls to AdServices framework (this is already guarded by the `if (@available(14.3` check, so we can just call the method directly
- Fixed incorrect passing of error pointer instead of memory address which had been obfuscated by the use of reflection
- Smoke test in iOS and tvOS test app
- Closes https://go.mparticle.com/work/SQDSDKS-6525

fix: Remove deprecated iAd framework

---

mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Network/MPConnector.m
mParticle-Apple-SDK/mParticle.m

- Added an option to disable certificate pinning, even in production.
- Tested in sample app
First Fresh app in development
Second sabotaged certs
Third used existing disabled in development to successfully upload
Fourth switched to Production to confirm it failed with bad certs as expected
Fifth tested change by enabling 'disabledPinning' in production
- Closes https://go.mparticle.com/work/SQDSDKS-6408

feat: Add Option to Disable Certificate Pinning

---

UnitTests/MPKitContainerTests.m
UnitTests/MParticleTests.m
UnitTests/NSNumber+MPFormatterTests.m
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Ecommerce/MPProduct.m
mParticle-Apple-SDK/Ecommerce/MPPromotion.m
mParticle-Apple-SDK/Ecommerce/MPTransactionAttributes.m
mParticle-Apple-SDK/Identity/FilteredMParticleUser.m
mParticle-Apple-SDK/Kits/MPEventProjection.mm
mParticle-Apple-SDK/Kits/MPKitConfiguration.mm
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/MParticleSwift.h
mParticle-Apple-SDK/Utils/MPIUserDefaults.m
mParticle-Apple-SDK/Utils/MPStateMachine.m
mParticle-Apple-SDK/mParticle.m

We have an internal header called `Swift.h` used as a wrapper import. Due to it being project level (aka internal), it was thought the generic file name would not cause issues, but due to the way Expo does builds, it conflicts with their own `Swift.h` header.
This change renames that internal header and updates all imports statements.
- Tested local build in Xcode
- Manually updated Expo test app dependency to use this change and confirmed successful build and run `npx expo run:ios`
- Closes https://go.mparticle.com/work/SQDSDKS-6578

fix: Rename internal Swift.h header to avoid Expo conflicts

---

UnitTests/MPBackendControllerTests.m
UnitTests/MPConnectorTests.m
UnitTests/MPDataModelTests.m
UnitTests/MPNetworkCommunicationTests.m
UnitTests/MPPersistenceControllerTests.mm
UnitTests/MPURLRequestBuilderTests.m
UnitTests/MPUploadBuilderTests.m
mParticle-Apple-SDK/Data Model/MPDataModelAbstract.h
mParticle-Apple-SDK/Data Model/MPUpload.h
mParticle-Apple-SDK/Data Model/MPUpload.m
mParticle-Apple-SDK/Identity/MPIdentityApi.m
mParticle-Apple-SDK/MPBackendController.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/Network/MPConnector.h
mParticle-Apple-SDK/Network/MPConnector.m
mParticle-Apple-SDK/Network/MPConnectorProtocol.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.h
mParticle-Apple-SDK/Network/MPNetworkCommunication.m
mParticle-Apple-SDK/Network/MPURLRequestBuilder.h
mParticle-Apple-SDK/Network/MPURLRequestBuilder.m
mParticle-Apple-SDK/Persistence/MPDatabaseMigrationController.m
mParticle-Apple-SDK/Persistence/MPPersistenceController.h
mParticle-Apple-SDK/Persistence/MPPersistenceController.mm
mParticle-Apple-SDK/Utils/MPUploadBuilder.h
mParticle-Apple-SDK/Utils/MPUploadBuilder.m
mParticle-Apple-SDK/mParticle.m

This is an updated implementation of workspace switching. This significantly reduces the amount of time it will take to switch workspaces, since only upload batching is performed before the switch, and any remaining batches are uploaded later.
- Tested extensively using a test app sending events to two different workspaces in addition to unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6593

feat: Workspace switching redux

---

mParticle-Apple-SDK/Data Model/MPUpload.h
mParticle-Apple-SDK/Data Model/MPUpload.m
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/MPBackendController.h
mParticle-Apple-SDK/MPBackendController.m
mParticle-Apple-SDK/MPIConstants.h
mParticle-Apple-SDK/MPIConstants.m
mParticle-Apple-SDK/Utils/MPIUserDefaults.h
mParticle-Apple-SDK/Utils/MPIUserDefaults.m
mParticle-Apple-SDK/mParticle.m

- While working on the previous workspace switching feature, I found this edge case where launching the app with a new workspace (instead of calling switchWorkspace while app is running) will result in any waiting, un-batched messages  to be uploaded to the new workspace instead of the previous one. 
- Tested with 2 workspaces and confirmed un-batched events from previous workspace upload to the previous workspace as intended. 
- Closes https://go.mparticle.com/work/SQDSDKS-6648

fix: Properly attribute events when workspace switches on new launch

---

mParticle-Apple-SDK/MPBackendController.m

- Do not automatically start a new session after we close out an idle background session.
- Tested in sample app using music player to test activity in background
- Closes https://go.mparticle.com/work/SQDSDKS-6724

fix: Prevent Repeated Sessions on active Background

---

mParticle-Apple-SDK/Utils/MPStateMachine.m

Fix for potential crash in `MPStateMachine` when entering the foreground due to potential null pointer dereference. 
Smoke tested E2E using test app including backgrounding/foregrounding
I also confirmed via logging pointers that the same object/pointer/address is passed into the `addObserver:` calls. 
- Closes https://go.mparticle.com/work/SQDSDKS-6853

fix: Potential crash in MPStateMachine when entering foreground

---

UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/mParticle.m

- Bool parameter on setOptOut was not being sent.
- Tested locally on simulator and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6839

fix: Fix set opt out for kits

---

mParticle-Apple-SDK/Utils/MPConvertJS.swift

- Change MPConvertJS.identityApiRequest parameter nullability
- Ran static analyzer and it now passes and I confirmed the code did require a nullable parameter
- Closes https://go.mparticle.com/work/6861

refactor: Change MPConvertJS.identityApiRequest parameter nullability

---

mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/MPBackendController.m

- InitializeKits doesn't need to be called on the main thread
- Tested in simulator with several of our most used kits
- Closes https://go.mparticle.com/work/SQDSDKS-6616

refactor: Initialize Kits in Background Thread

---

README.md

- Our kits list is out of date for SPM and carthage support and there are some missing kits that were not added in the list (Firebase/GA4 and Foresee) 
- [N/A] Was this tested locally? If not, explain why.
- readme update only
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5626

docs: Update SPM/Carthage supported kits

---

mParticle-Apple-SDK/Utils/MPStateMachine.m

- Deal with edge case that may have caused fewer first install reports than users
- Tested in local sample app. Could not recreate original issue but confirmed this change doesn't cause any new issues
- Closes https://go.mparticle.com/work/SQDSDKS-6899

fix: Address firstInstall Edge Case

---

UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK/Data Model/MPForwardRecord.m
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/Kits/MPKitFilter.h
mParticle-Apple-SDK/Kits/MPKitFilter.m

- When a kit have custom mappings (such as AppsFlyer and GA4 firebase) we currently forward the mapped event name to the UI in livestream and event forwarding view where only the outbound is increased while the inbound is 0, while for the original event the inbound is increased and the output will not. This fix will forward the reporting issue by only forwarding the reporting of the original event in the outbound and will not create a new event to the schema and only increase the outbound.
- [Y] Was this tested locally? If not, explain why.
- partial-E2E testing with breakpoints in the AppsFlyer kit to see if the mapped event forwarded as expected as well as full E2E testing on the UI to see if the original event is reported as is.
- Unit testing cases added to check if projectedEvents …

fix: forward original event names to UI for kits with mapped events

---

UnitTests/MPBackendControllerTests.m
mParticle-Apple-SDK/MPBackendController.m

- Setting identity to nil in an identity request was causing a crash once it was reaching swift code
- Tested locally and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-7144

fix: Issue when setting Identity Attributes to nil

---

mParticle-Apple-SDK/MPConstants.swift
mParticle-Apple-SDK/mParticle.m

- Ensure MPUserDefaults is always initialized with valid instance of Identity.
- Closes https://go.mparticle.com/work/SQDSDKS-7163

fix: Ensure UserDefaults has valid instance of Identity

---

UnitTests/MPRoktTests.m
mParticle-Apple-SDK/mParticle.m

- Allows User Attribute Mapping via the Kit Container/Kit Configuration in the SDK.
- Tested locally and through unit tests. Also tested out unrelated functionality and confirmed in the live stream.
- Closes https://go.mparticle.com/work/SQDSDKS-7184

feat: Add user attribute mapping

---

UnitTests/MPRoktTests.m
mParticle-Apple-SDK/mParticle.m

- Updated the `selectPlacements` logic to add the sandbox attribute if it hasn't already been included by the client. The value of this attribute is based off the environment.
- Tested manually and through existing and updated unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-7205

feat: Automatically include sandbox in MPRokt Attributes

---

UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK/Include/MPEnums.h
mParticle-Apple-SDK/Include/MPKitContainer.h
mParticle-Apple-SDK/Include/mParticle.h
mParticle-Apple-SDK/Kits/MPKitContainer.mm
mParticle-Apple-SDK/mParticle.m

- Added a disabledKits property to mParticleOptions that prevents an kit with a matching kit ID from being initialized or sent events.
- Tested locally and through sample app
- Closes https://go.mparticle.com/work/SQDSDKS-7214

feat: Add disabledKits option to MParticleOptions

---

mParticle-Apple-SDK/Utils/MPDevice.swift

- A customer reported that the IDFV comes in as a random UUID every time the mParticle SDK is initialized, I was able to reproduce and confirm the behavior and applied the fix below
- E2E tested
- Closes https://go.mparticle.com/work/REPLACEME

fix: assign correct IDFV instead of random UUID

---

UnitTests/MPRoktTests.m
mParticle-Apple-SDK/MPRokt.m

- After a developer calls selectPlacements with email, we should check to see if email is on the user yet.  If it isn’t, we should call identify with email (along with all other current user identities)
- Tested live and with unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-7247

feat: Identify if Provided Email in Rokt SelectPlacements

---

UnitTests/MPAppNotificationHandlerTests.m
mParticle-Apple-SDK/AppNotifications/MPAppNotificationHandler.m

- Prevent nil webpageURL from crashing SDK
- Tested through unit tests and standard smoke tests though was not able to recreate the original crash prior to fix.
- Closes https://go.mparticle.com/work/SQDSDKS-7334

fix: MPAppNotificationHandler webpageURL issue

---

UnitTests/MPBackendControllerTests.m
mParticle-Apple-SDK/MPBackendController.m

- an optional Objective C value  could cause a crash when being sent to the Swift Code. This prevents that possiblity.
- Tested locally and added unit tests that would have caught this crash
- Closes https://go.mparticle.com/work/PRODRDMP-7722

fix: Prevent Issue When NSUserActivity webpageURL is nil

---

mParticle-Apple-SDK.xcodeproj/project.pbxproj

- Whenever I opened up the mparticle-apple-sdk project xCode would immediately crash. 
still crashed 
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------
Process:               Xcode [3588]
Path:                  /Applications/Xcode-beta.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               26.0 (24141.31)
Build Info: …
```

fix: Prevent Apple Xcode Crash

---

.github/workflows/build-and-lint.yml

- Add notification after PR completes
- N/A
- N/A

chore: Add PR GChat notification

---

Example/mParticleExample/AppDelegate.m
Example/mParticleExample/ViewController.m
UnitTests/MPKitContainerTests.m
mParticle-Apple-SDK/Include/MPRokt.h
mParticle-Apple-SDK/MPRokt.m

- Create Rokt.close method and passthrough to kit
- Changed app delegate key placeholders for easy selection
https://github.com/user-attachments/assets/9c78701f-0317-4e77-b34b-282741d396a7
- Tested using the Example app and creating a new entry for auto close
- Closes https://go.mparticle.com/work/SQDSDKS-7443

feat: Create Rokt.close method

---

mParticle-Apple-SDK.xcodeproj/project.pbxproj

- Changed the bundle ID of the NoLocation target so that it was unique from the regular SDK. Them being the same was causing issue when customers tried to switch between them.
- This is hard to confirm as a fix without releasing but from my tests it should fix the problem for SPM and its best practice for the bundle id to be different for each target. I was able to confirm a build in this scenario using cocoapods pointing to this branch.
- Closes https://go.mparticle.com/work/SQDSDKS-7527

fix: Update Bundle Id for No Location

---

UnitTests/MPRoktTests.m
mParticle-Apple-SDK/MPRokt.m

- The core sdk changes required to support hashed emails provided in a select placements call. 
- Confirmed on sample app and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-7555

feat: Handle Hashed Email for Rokt

---

UnitTests/MPRoktTests.m
mParticle-Apple-SDK/MPRokt.m

- Updated according to new specs
(1 is the only one that affects the core sdk)
1.  If other is a current identity, and the developer passes  emailsha256 attribute with a different value from other identity to selectPlacements, log a warning to the user, and call identify with other using the value from emailsha256
2. Never remove other from the attributes passed to selectPlacements because it's considered a normal attribute
3. If email identity exists on the user, and emailsha256 attribute is passed to selectPlacements, do not send email attribute to the selectPlacements call.  OR if email identity and other identity exist on the user, only pass emailsha256 attribute with the value from other identity
- Tested on simulator and with unit tests
- Closes …

feat: Update Hashed Email for Rokt

---

README.md

- Replaces an outdated link to the iOS SDK IDSync docs at docs.mparticle.com
- Closes https://go.mparticle.com/work/REPLACEME

docs: Updates link to IDSync docs in README

---

mParticle-Apple-SDK/Utils/MPDevice.swift
mParticle-Apple-SDK/Utils/MPUploadSettings.swift

- While namespacing is not a concern when developing with Frameworks in Swift or Objective C in isolation it can cause issues in Objective C frameworks like NSSecureCoding when bridging from Swift. By adding the annotation @objc(name), namespacing is ignored even if we are working with Swift. 
Here's the latest error message the client was running into
```
[21:45:29]: ▸ Testing failed:
[21:45:29]: ▸ 'MPLocationManager_PRIVATE' has different definitions in different modules; first difference is definition in module 'mParticle_Apple_SDK_NoLocation.Swift' found method
[21:45:29]: ▸ 'MPDevice' has different definitions in different modules; first difference is definition in module 'mParticle_Apple_SDK.Swift' found property 'carrier'
[21:45:29]: ▸ Command SwiftCompile failed with a nonzero …
```

fix: Prevent Swift Name Spacing for Encodable Objects

---

Scripts/check_coverage.py
Scripts/check_coverage.sh

- This PR contains two script files `check_coverage.sh` and `check_coverage.py` to build project coverage report
- To build report  you can run `check_coverage.sh` from build folder.
- `check_coverage.py` contains `COVERAGE_THRESHOLD` which is used to highlight files with red if coverage less the threshold.
- Script doesn't display files which have 100% coverage
- [*] Was this tested locally? If not, explain why.
- to check project test coverage you can run `check_coverage.sh` from build folder.
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-7484

feat: Add scripts to analyze project test coverage

---

.github/dependabot.yml

- Add prefix for dependabot
- N/A
- Closes N/A

chore: Add prefix for dependabot

---

UnitTests/MParticle+PrivateMethods.h
UnitTests/MParticleTestsSwift.swift
UnitTests/mParticle_iOS_SDKTests-Bridging-Header.h
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/mParticle.m

- This is the first PR in the series.
- In this PR, the callback logic has been extracted into a separate method and is now covered with tests.
- I suggest reviewing the PR commit by commit for clarity.
- It was also checked with both the Example and Higgs apps
- Part of https://rokt.atlassian.net/browse/SDKE-61

feat: SDKE-61 Extract and test callback logic. Part 1

---

UnitTests/MPUserDefaultsMock.swift
UnitTests/MParticle+PrivateMethods.h
UnitTests/MParticleTestsSwift.swift
UnitTests/SettingsProviderMock.h
UnitTests/SettingsProviderMock.m
UnitTests/SettingsProviderTests.swift
UnitTests/mParticle_iOS_SDKTests-Bridging-Header.h
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/SettingsProvider.h
mParticle-Apple-SDK/SettingsProvider.m
mParticle-Apple-SDK/Utils/MPUserDefaults.swift
mParticle-Apple-SDK/mParticle.m

This PR is second PR from the series. Previous https://github.com/mParticle/mparticle-apple-sdk/pull/394
- startWithKeyCallback logic was extracted to separate method and covered with tests
- add protocol for MPUserDefaults
- add mock for MPUserDefaults
- add mock for SettingsProvider
- affected code was covered with tests
- apps were launched and checked that we receive events as expected
- Related to https://rokt.atlassian.net/browse/SDKE-61

feat: SDKE-61 Extract and test callback logic. Part 2

---

UnitTests/MParticle+PrivateMethods.h
UnitTests/MParticleTestsSwift.swift
UnitTests/Mocks/MPPersistenceControllerMock.swift
UnitTests/mParticle_iOS_SDKTests-Bridging-Header.h
mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Include/MPPersistenceController.h
mParticle-Apple-SDK/mParticle.m

This is the second PR in a series focused on improving testability. Its main goal is to decouple testing code from Swift tests and establish a foundation for better testing practices. Previous PR: https://github.com/mParticle/mparticle-apple-sdk/pull/403
Introduced two new protocols and their mock implementations.
Added a test to ensure the mocks behave as expected.
- Closes https://rokt.atlassian.net/browse/SDKE-119

feat: SDKE-119 Create protocols for testability. Part 3

---

mParticle-Apple-SDK.xcodeproj/project.pbxproj
mParticle-Apple-SDK/Executor.h
mParticle-Apple-SDK/Executor.m
mParticle-Apple-SDK/mParticle.m

This PR extracts the executor logic into a dedicated Executor class implementing ExecutorProtocol. The goal is to improve testability, reduce coupling with MParticle, and centralize queue and threading logic in a single component.
It is first PR from series.
Previously, queue handling (messageQueue and main thread execution) was hard-coded inside MParticle, making the class tightly coupled and difficult to test. By moving this logic into a separate Executor class, we:
Enable easier unit testing by mocking ExecutorProtocol.
Reduce complexity and dependencies inside MParticle.
Improve maintainability and lay the groundwork for future architectural improvements.
- Related to …

feat: SDKE-64 Improve mParticle.m test coverage in swift

---

UnitTests/MParticle+PrivateMethods.h
UnitTests/MParticleTestsSwift.swift
mParticle-Apple-SDK/Logger/MPLogger.swift
mParticle-Apple-SDK/mParticle.m

This is the 3 PR in the series aimed at improving the test coverage of mParticle.m. The first PR is https://github.com/mParticle/mparticle-apple-sdk/pull/407
- add more tests
- Related to https://rokt.atlassian.net/browse/SDKE-64

feat: SDKE-64 Improve mParticle.m test coverage in swift 3

---

mParticle-Apple-SDK/MPAttributionResult+MParticlePrivate.m

- MPAttributionResult wasn't synthesize setter because private header wasn't imported, but the core of the problem was that MPKitAPI class was using private property which wasn't available to them. We should consider to make this property readwrite in public interface instead creating private category or import related header to all places where we create this new private category.
- create Tech Dept ticket https://rokt.atlassian.net/browse/SDKE-236
- Closes https://rokt.atlassian.net/browse/SDKE-235

Fix: SDKE-235 Crash in MPKitAPI.h 

---

.github/workflows/sdk-release.yml

- This PR updates the repository to support newly agreed upon standards in regards to branching and release strategy.
- This is a github action and therefor can't be ran locally
- Closes https://rokt.atlassian.net/browse/SDKE-164

ci: Update Release YML to release from Main

---

UnitTests/MParticleTestsSwift.swift
UnitTests/Mocks/MPBackendControllerMock.swift

- Refactored tests to make them simpler.
- Added tests for the breadcrumb method.
- Closes https://rokt.atlassian.net/browse/SDKE-255

test: SDKE-255 Add test coverage for add test coverage for leave breadcrumb method

---

CONTRIBUTING.md
README.md
RELEASE.md

- Updated README.md with consistent formatting. Added CONTRIBUTING.md to define contribution guidelines. Added RELEASING.md to document the release process.To standardize documentation structure with other repositories.
- Closes https://go/j/SDKE-265

docs: Updated readme file and add contributing and release file
